### ISSUE TITLE
`ltextras:mob_controller` registry entry does not exist

### ISSUE THREAD

**Issue by NotActuallyTerry** [LoveTropics/LTExtras#3]
Full stacktrace:
```st
	Mod File: LTExtras-1.2.0-release+9.jar
	Failure message: LTExtras (ltextras) encountered an error during the error event phase
		java.lang.RuntimeException: Unexpected error while registering entry ltextras:mob_controller to registry minecraft:block_entity_type
	Mod Version: 1.2.0-release+9
	Mod Issue URL: https://github.com/LoveTropics/LTExtras/issues
	Exception message: java.lang.NullPointerException: Registry entry not present: ltextras:mob_controller
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at com.lovetropics.extras.repack.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:89) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at com.lovetropics.extras.repack.registrate.util.entry.LazyRegistryEntry.get(LazyRegistryEntry.java:25) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
	at com.lovetropics.extras.repack.registrate.builders.BlockEntityBuilder.createEntry(BlockEntityBuilder.java:138) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at com.lovetropics.extras.repack.registrate.builders.BlockEntityBuilder.createEntry(BlockEntityBuilder.java:39) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at net.minecraftforge.common.util.Lazy$Fast.get(Lazy.java:55) ~[forge-1.18.2-40.1.54-universal.jar%2364!/:?] {re:classloading}
	at com.lovetropics.extras.repack.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:146) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at com.lovetropics.extras.repack.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:263) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading}
	at com.lovetropics.extras.repack.registrate.AbstractRegistrate$1EventProxy.onRegister(AbstractRegistrate.java:209) ~[LTExtras-1.2.0-release+9.jar%2354!/:1.2.0-release+9] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_17_1EventProxy_onRegister_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.54.jar%2361!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:201) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.54.jar%2360!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.1.54-universal.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.1.54-universal.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.1.54-universal.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by NotActuallyTerry** [comment]
Fixed in [9104b3e](https://github.com/LoveTropics/LTExtras/commit/9104b3ed16eeb797776c77233ed5c9122b8ea059)
